set_property SRC_FILE_INFO {cfile:F:/ProyectosARTY/DDR_Access/DDR_Access.srcs/constrs_1/new/design_1_wrapper.xdc rfile:../../../DDR_Access.srcs/constrs_1/new/design_1_wrapper.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 32768 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[0]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[1]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[2]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[3]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[4]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[5]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[6]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[7]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[8]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[9]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[10]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[11]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[12]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[13]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[14]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[15]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[16]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[17]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[18]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[19]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[20]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[21]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[22]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[23]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[24]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[25]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[26]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[27]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[28]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[29]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[30]} {design_1_i/axi_vfifo_ctrl_0/m_axi_wdata[31]}]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[0]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[1]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[2]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[3]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[4]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[5]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[6]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[7]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[8]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[9]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[10]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[11]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[12]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[13]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[14]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[15]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[16]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[17]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[18]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[19]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[20]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[21]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[22]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[23]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[24]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[25]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[26]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[27]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[28]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[29]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[30]} {design_1_i/axi_vfifo_ctrl_0/m_axis_tdata[31]}]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[0]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[1]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[2]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[3]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[4]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[5]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[6]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[7]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[8]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[9]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[10]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[11]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[12]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[13]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[14]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[15]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[16]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[17]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[18]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[19]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[20]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[21]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[22]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[23]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[24]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[25]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[26]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[27]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[28]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[29]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[30]} {design_1_i/axi_vfifo_ctrl_0/s_axis_tdata[31]}]]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/fifo_generator_1/s_axis_tdata[0]} {design_1_i/fifo_generator_1/s_axis_tdata[1]} {design_1_i/fifo_generator_1/s_axis_tdata[2]} {design_1_i/fifo_generator_1/s_axis_tdata[3]} {design_1_i/fifo_generator_1/s_axis_tdata[4]} {design_1_i/fifo_generator_1/s_axis_tdata[5]} {design_1_i/fifo_generator_1/s_axis_tdata[6]} {design_1_i/fifo_generator_1/s_axis_tdata[7]} {design_1_i/fifo_generator_1/s_axis_tdata[8]} {design_1_i/fifo_generator_1/s_axis_tdata[9]} {design_1_i/fifo_generator_1/s_axis_tdata[10]} {design_1_i/fifo_generator_1/s_axis_tdata[11]} {design_1_i/fifo_generator_1/s_axis_tdata[12]} {design_1_i/fifo_generator_1/s_axis_tdata[13]} {design_1_i/fifo_generator_1/s_axis_tdata[14]} {design_1_i/fifo_generator_1/s_axis_tdata[15]} {design_1_i/fifo_generator_1/s_axis_tdata[16]} {design_1_i/fifo_generator_1/s_axis_tdata[17]} {design_1_i/fifo_generator_1/s_axis_tdata[18]} {design_1_i/fifo_generator_1/s_axis_tdata[19]} {design_1_i/fifo_generator_1/s_axis_tdata[20]} {design_1_i/fifo_generator_1/s_axis_tdata[21]} {design_1_i/fifo_generator_1/s_axis_tdata[22]} {design_1_i/fifo_generator_1/s_axis_tdata[23]} {design_1_i/fifo_generator_1/s_axis_tdata[24]} {design_1_i/fifo_generator_1/s_axis_tdata[25]} {design_1_i/fifo_generator_1/s_axis_tdata[26]} {design_1_i/fifo_generator_1/s_axis_tdata[27]} {design_1_i/fifo_generator_1/s_axis_tdata[28]} {design_1_i/fifo_generator_1/s_axis_tdata[29]} {design_1_i/fifo_generator_1/s_axis_tdata[30]} {design_1_i/fifo_generator_1/s_axis_tdata[31]}]]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/fifo_generator_1/m_axis_tdata[0]} {design_1_i/fifo_generator_1/m_axis_tdata[1]} {design_1_i/fifo_generator_1/m_axis_tdata[2]} {design_1_i/fifo_generator_1/m_axis_tdata[3]} {design_1_i/fifo_generator_1/m_axis_tdata[4]} {design_1_i/fifo_generator_1/m_axis_tdata[5]} {design_1_i/fifo_generator_1/m_axis_tdata[6]} {design_1_i/fifo_generator_1/m_axis_tdata[7]} {design_1_i/fifo_generator_1/m_axis_tdata[8]} {design_1_i/fifo_generator_1/m_axis_tdata[9]} {design_1_i/fifo_generator_1/m_axis_tdata[10]} {design_1_i/fifo_generator_1/m_axis_tdata[11]} {design_1_i/fifo_generator_1/m_axis_tdata[12]} {design_1_i/fifo_generator_1/m_axis_tdata[13]} {design_1_i/fifo_generator_1/m_axis_tdata[14]} {design_1_i/fifo_generator_1/m_axis_tdata[15]} {design_1_i/fifo_generator_1/m_axis_tdata[16]} {design_1_i/fifo_generator_1/m_axis_tdata[17]} {design_1_i/fifo_generator_1/m_axis_tdata[18]} {design_1_i/fifo_generator_1/m_axis_tdata[19]} {design_1_i/fifo_generator_1/m_axis_tdata[20]} {design_1_i/fifo_generator_1/m_axis_tdata[21]} {design_1_i/fifo_generator_1/m_axis_tdata[22]} {design_1_i/fifo_generator_1/m_axis_tdata[23]} {design_1_i/fifo_generator_1/m_axis_tdata[24]} {design_1_i/fifo_generator_1/m_axis_tdata[25]} {design_1_i/fifo_generator_1/m_axis_tdata[26]} {design_1_i/fifo_generator_1/m_axis_tdata[27]} {design_1_i/fifo_generator_1/m_axis_tdata[28]} {design_1_i/fifo_generator_1/m_axis_tdata[29]} {design_1_i/fifo_generator_1/m_axis_tdata[30]} {design_1_i/fifo_generator_1/m_axis_tdata[31]}]]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/fifo_generator_0/s_axis_tdata[0]} {design_1_i/fifo_generator_0/s_axis_tdata[1]} {design_1_i/fifo_generator_0/s_axis_tdata[2]} {design_1_i/fifo_generator_0/s_axis_tdata[3]} {design_1_i/fifo_generator_0/s_axis_tdata[4]} {design_1_i/fifo_generator_0/s_axis_tdata[5]} {design_1_i/fifo_generator_0/s_axis_tdata[6]} {design_1_i/fifo_generator_0/s_axis_tdata[7]} {design_1_i/fifo_generator_0/s_axis_tdata[8]} {design_1_i/fifo_generator_0/s_axis_tdata[9]} {design_1_i/fifo_generator_0/s_axis_tdata[10]} {design_1_i/fifo_generator_0/s_axis_tdata[11]} {design_1_i/fifo_generator_0/s_axis_tdata[12]} {design_1_i/fifo_generator_0/s_axis_tdata[13]} {design_1_i/fifo_generator_0/s_axis_tdata[14]} {design_1_i/fifo_generator_0/s_axis_tdata[15]} {design_1_i/fifo_generator_0/s_axis_tdata[16]} {design_1_i/fifo_generator_0/s_axis_tdata[17]} {design_1_i/fifo_generator_0/s_axis_tdata[18]} {design_1_i/fifo_generator_0/s_axis_tdata[19]} {design_1_i/fifo_generator_0/s_axis_tdata[20]} {design_1_i/fifo_generator_0/s_axis_tdata[21]} {design_1_i/fifo_generator_0/s_axis_tdata[22]} {design_1_i/fifo_generator_0/s_axis_tdata[23]} {design_1_i/fifo_generator_0/s_axis_tdata[24]} {design_1_i/fifo_generator_0/s_axis_tdata[25]} {design_1_i/fifo_generator_0/s_axis_tdata[26]} {design_1_i/fifo_generator_0/s_axis_tdata[27]} {design_1_i/fifo_generator_0/s_axis_tdata[28]} {design_1_i/fifo_generator_0/s_axis_tdata[29]} {design_1_i/fifo_generator_0/s_axis_tdata[30]} {design_1_i/fifo_generator_0/s_axis_tdata[31]}]]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/fifo_generator_0/m_axis_tdata[0]} {design_1_i/fifo_generator_0/m_axis_tdata[1]} {design_1_i/fifo_generator_0/m_axis_tdata[2]} {design_1_i/fifo_generator_0/m_axis_tdata[3]} {design_1_i/fifo_generator_0/m_axis_tdata[4]} {design_1_i/fifo_generator_0/m_axis_tdata[5]} {design_1_i/fifo_generator_0/m_axis_tdata[6]} {design_1_i/fifo_generator_0/m_axis_tdata[7]} {design_1_i/fifo_generator_0/m_axis_tdata[8]} {design_1_i/fifo_generator_0/m_axis_tdata[9]} {design_1_i/fifo_generator_0/m_axis_tdata[10]} {design_1_i/fifo_generator_0/m_axis_tdata[11]} {design_1_i/fifo_generator_0/m_axis_tdata[12]} {design_1_i/fifo_generator_0/m_axis_tdata[13]} {design_1_i/fifo_generator_0/m_axis_tdata[14]} {design_1_i/fifo_generator_0/m_axis_tdata[15]} {design_1_i/fifo_generator_0/m_axis_tdata[16]} {design_1_i/fifo_generator_0/m_axis_tdata[17]} {design_1_i/fifo_generator_0/m_axis_tdata[18]} {design_1_i/fifo_generator_0/m_axis_tdata[19]} {design_1_i/fifo_generator_0/m_axis_tdata[20]} {design_1_i/fifo_generator_0/m_axis_tdata[21]} {design_1_i/fifo_generator_0/m_axis_tdata[22]} {design_1_i/fifo_generator_0/m_axis_tdata[23]} {design_1_i/fifo_generator_0/m_axis_tdata[24]} {design_1_i/fifo_generator_0/m_axis_tdata[25]} {design_1_i/fifo_generator_0/m_axis_tdata[26]} {design_1_i/fifo_generator_0/m_axis_tdata[27]} {design_1_i/fifo_generator_0/m_axis_tdata[28]} {design_1_i/fifo_generator_0/m_axis_tdata[29]} {design_1_i/fifo_generator_0/m_axis_tdata[30]} {design_1_i/fifo_generator_0/m_axis_tdata[31]}]]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list design_1_i/axi_vfifo_ctrl_0/m_axis_tready]]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list design_1_i/fifo_generator_0/m_axis_tready]]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list design_1_i/axi_vfifo_ctrl_0/m_axis_tvalid]]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list design_1_i/fifo_generator_0/m_axis_tvalid]]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list design_1_i/fifo_generator_1/m_axis_tvalid]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list design_1_i/axi_vfifo_ctrl_0/s_axis_tready]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list design_1_i/fifo_generator_0/s_axis_tready]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list design_1_i/fifo_generator_1/s_axis_tready]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
